# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGroupBox, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QTabWidget, QTextEdit, QWidget)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(700, 500)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(700, 500))
        MainWindow.setMaximumSize(QSize(700, 500))
        font = QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionOpen_File = QAction(MainWindow)
        self.actionOpen_File.setObjectName(u"actionOpen_File")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(5, 5, 186, 306))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(False)
        self.groupBox.setFont(font1)
        self.groupBox.setAutoFillBackground(True)
        self.comboBox_SPort = QComboBox(self.groupBox)
        self.comboBox_SPort.setObjectName(u"comboBox_SPort")
        self.comboBox_SPort.setGeometry(QRect(80, 65, 91, 26))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 65, 66, 26))
        self.label.setFont(font1)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 105, 66, 26))
        self.label_2.setFont(font1)
        self.comboBox_BRate = QComboBox(self.groupBox)
        self.comboBox_BRate.setObjectName(u"comboBox_BRate")
        self.comboBox_BRate.setGeometry(QRect(80, 105, 91, 26))
        self.comboBox_BSize = QComboBox(self.groupBox)
        self.comboBox_BSize.setObjectName(u"comboBox_BSize")
        self.comboBox_BSize.setGeometry(QRect(80, 145, 91, 26))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 145, 66, 26))
        self.label_3.setFont(font1)
        self.comboBox_SBit = QComboBox(self.groupBox)
        self.comboBox_SBit.setObjectName(u"comboBox_SBit")
        self.comboBox_SBit.setGeometry(QRect(80, 185, 91, 26))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 185, 66, 26))
        self.label_4.setFont(font1)
        self.comboBox_PBit = QComboBox(self.groupBox)
        self.comboBox_PBit.setObjectName(u"comboBox_PBit")
        self.comboBox_PBit.setGeometry(QRect(80, 225, 91, 26))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 225, 66, 26))
        self.label_5.setFont(font1)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 25, 66, 26))
        self.label_7.setFont(font1)
        self.pushButton_Check = QPushButton(self.groupBox)
        self.pushButton_Check.setObjectName(u"pushButton_Check")
        self.pushButton_Check.setGeometry(QRect(80, 25, 91, 26))
        self.pushButton_Open = QPushButton(self.groupBox)
        self.pushButton_Open.setObjectName(u"pushButton_Open")
        self.pushButton_Open.setGeometry(QRect(15, 265, 71, 31))
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(False)
        self.pushButton_Open.setFont(font2)
        self.pushButton_Close = QPushButton(self.groupBox)
        self.pushButton_Close.setObjectName(u"pushButton_Close")
        self.pushButton_Close.setGeometry(QRect(100, 265, 71, 31))
        self.pushButton_Close.setFont(font2)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(5, 315, 691, 141))
        self.groupBox_2.setAutoFillBackground(True)
        self.tabWidget = QTabWidget(self.groupBox_2)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 20, 576, 121))
        self.single = QWidget()
        self.single.setObjectName(u"single")
        self.textEdit_SSend = QTextEdit(self.single)
        self.textEdit_SSend.setObjectName(u"textEdit_SSend")
        self.textEdit_SSend.setGeometry(QRect(1, 1, 568, 91))
        self.textEdit_SSend.setFrameShape(QFrame.Panel)
        self.textEdit_SSend.setFrameShadow(QFrame.Sunken)
        self.tabWidget.addTab(self.single, "")
        self.multi = QWidget()
        self.multi.setObjectName(u"multi")
        self.tabWidget.addTab(self.multi, "")
        self.protocol = QWidget()
        self.protocol.setObjectName(u"protocol")
        self.tabWidget.addTab(self.protocol, "")
        self.pushButton_Send = QPushButton(self.groupBox_2)
        self.pushButton_Send.setObjectName(u"pushButton_Send")
        self.pushButton_Send.setGeometry(QRect(590, 50, 81, 31))
        self.pushButton_SClear = QPushButton(self.groupBox_2)
        self.pushButton_SClear.setObjectName(u"pushButton_SClear")
        self.pushButton_SClear.setGeometry(QRect(590, 95, 81, 31))
        self.checkBox_Newline = QCheckBox(self.groupBox_2)
        self.checkBox_Newline.setObjectName(u"checkBox_Newline")
        self.checkBox_Newline.setGeometry(QRect(500, 19, 79, 21))
        self.checkBox_SHexmode = QCheckBox(self.groupBox_2)
        self.checkBox_SHexmode.setObjectName(u"checkBox_SHexmode")
        self.checkBox_SHexmode.setGeometry(QRect(590, 20, 79, 21))
        self.lineEdit_Cycle = QLineEdit(self.groupBox_2)
        self.lineEdit_Cycle.setObjectName(u"lineEdit_Cycle")
        self.lineEdit_Cycle.setGeometry(QRect(405, 20, 71, 21))
        self.checkBox_Cycle = QCheckBox(self.groupBox_2)
        self.checkBox_Cycle.setObjectName(u"checkBox_Cycle")
        self.checkBox_Cycle.setGeometry(QRect(325, 20, 81, 21))
        self.groupBox_21 = QGroupBox(self.centralwidget)
        self.groupBox_21.setObjectName(u"groupBox_21")
        self.groupBox_21.setGeometry(QRect(200, 5, 496, 306))
        self.groupBox_21.setAutoFillBackground(True)
        self.groupBox_21.setFlat(False)
        self.textEdit_Receive = QTextEdit(self.groupBox_21)
        self.textEdit_Receive.setObjectName(u"textEdit_Receive")
        self.textEdit_Receive.setGeometry(QRect(5, 20, 486, 251))
        self.textEdit_Receive.setFrameShape(QFrame.Panel)
        self.textEdit_Receive.setFrameShadow(QFrame.Sunken)
        self.textEdit_Receive.setReadOnly(True)
        self.checkBox_RHexmode = QCheckBox(self.groupBox_21)
        self.checkBox_RHexmode.setObjectName(u"checkBox_RHexmode")
        self.checkBox_RHexmode.setGeometry(QRect(395, 275, 79, 26))
        self.pushButton_RClear = QPushButton(self.groupBox_21)
        self.pushButton_RClear.setObjectName(u"pushButton_RClear")
        self.pushButton_RClear.setGeometry(QRect(305, 275, 71, 26))
        self.pushButton_RSave = QPushButton(self.groupBox_21)
        self.pushButton_RSave.setObjectName(u"pushButton_RSave")
        self.pushButton_RSave.setGeometry(QRect(210, 275, 71, 26))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 700, 23))
        self.menubar.setFont(font)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuFile.setFont(font)
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(u"menuAbout")
        self.menuAbout.setFont(font1)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionOpen_File.setText(QCoreApplication.translate("MainWindow", u"Open File", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"SerialPort", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"BaudRate", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"ByteSize", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"StopBits", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"ParityBits ", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"CheckPort", None))
        self.pushButton_Check.setText(QCoreApplication.translate("MainWindow", u"Check", None))
        self.pushButton_Open.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.pushButton_Close.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Send", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.single), QCoreApplication.translate("MainWindow", u"Single", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.multi), QCoreApplication.translate("MainWindow", u"Multi", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.protocol), QCoreApplication.translate("MainWindow", u"Protocol", None))
        self.pushButton_Send.setText(QCoreApplication.translate("MainWindow", u"Send", None))
        self.pushButton_SClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.checkBox_Newline.setText(QCoreApplication.translate("MainWindow", u"NewLine", None))
        self.checkBox_SHexmode.setText(QCoreApplication.translate("MainWindow", u"HexMode", None))
        self.lineEdit_Cycle.setText(QCoreApplication.translate("MainWindow", u"1000", None))
        self.checkBox_Cycle.setText(QCoreApplication.translate("MainWindow", u"Cycle(ms)", None))
        self.groupBox_21.setTitle(QCoreApplication.translate("MainWindow", u"Receive", None))
        self.checkBox_RHexmode.setText(QCoreApplication.translate("MainWindow", u"HexMode", None))
        self.pushButton_RClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.pushButton_RSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuAbout.setTitle(QCoreApplication.translate("MainWindow", u"About", None))
    # retranslateUi

